#!/usr/bin/env bash
#
# Copyright (C) 2023 
# Haytham Elkhoja 
# Mike Lyons
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License v2.0 as published by
# the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Latency Ninja.  If not, see <https://www.gnu.org/licenses/>.

# Include utility files
. inc/variables.sh
. inc/usage.sh
. inc/updater_utils.sh
. inc/arguments_utils.sh
. inc/sys_utils.sh
. inc/network_utils.sh
. inc/traffic_control_utils.sh
. inc/query_utils.sh

main() {
    check_system_requirements
    find_command_paths
    get_arguments "$@"
    parse_arguments 
    validate_arguments    
    rollback_required=1
    load_ifb_module
    rollback_everything silent
    display_params "applying"
    if [ "$direction" == "ingress" ] || [ "$direction" == "both" ]; then        
        create_virtual_interface "$ifb0_interface"
        bring_up_interface "$ifb0_interface"
        configure_ingress_traffic_controls "$eth_interface" "$ifb0_interface" src_ip[@] dst_ip[@] "$latency" "$jitter" "$packet_loss" "$duplicate" "$corrupt" "$reorder"
    fi
    if [ "$direction" == "egress" ] || [ "$direction" == "both" ]; then
        create_virtual_interface "$ifb1_interface"
        bring_up_interface "$ifb1_interface"        
        configure_egress_traffic_controls "$eth_interface" "$ifb1_interface" src_ip[@] dst_ip[@] "$latency" "$jitter" "$packet_loss" "$duplicate" "$corrupt" "$reorder"
    fi
    display_params "applied"
}

main "$@"